---
- name: Secure and setup remote host
  hosts: workstation
  gather_facts: false

  pre_tasks:
    - name: Wait for VM to fully boot and SSH to become available
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 300 # Total timeout of 5 minutes
        sleep: 10
        connect_timeout: 10
      retries: 30
      delay: 10
      register: connection_result
      ignore_errors: yes

    - name: Display connection status
      debug:
        msg: "SSH connection established successfully to {{ inventory_hostname }}:{{ ansible_port }}"
      when: connection_result is succeeded

  roles:
    - secure-vm
    - setup-vm
